spring:
  profiles:
  active:
  - dev
---
spring:
  profiles: dev
  application:
    name: microservicecloud-pancoit-config
---
spring:
  profiles: test
  application:
    name: microservicecloud-pancoit-config