spring:
  profiles:
  active:
  - dev
---
server:
  port: 8002
spring:
  profiles: dev
  application:
    name: microservicecloud-pancoit-config-dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
---
server:
  port: 8002
spring:
  profiles: test
  application:
    name: microservicecloud-pancoit-config-test

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
